import type { TileId } from "./glyphs";

/** Fictional clinic, patient and messages throughout. */
export const COPY = {
  en: {
    kicker: "Play · build",
    title: "Wire up a clinic assistant",
    lede: "A patient sends a voice note on LINE. Drag each part to the step it belongs to, or tap a part and then a step.",
    trayLabel: "Parts",
    trayEmpty: "All parts placed",
    idle: "Six parts, six steps. Read the step hints.",
    tiles: {
      line: "LINE",
      stt: "Speech to text",
      ts: "TypeScript",
      model: "Model",
      guard: "Guard",
      reply: "Reply",
    } as Record<TileId, string>,
    sockets: [
      "Where the message arrives",
      "Turns the voice note into words",
      "The service that runs the logic",
      "Drafts the answer",
      "Blocks what a clinic must not say",
      "Goes back to the patient",
    ],
    wrong: {
      line: "Not there. LINE is where the message comes in: step 1.",
      stt: "Not there. The voice note needs words first: step 2.",
      ts: "Not there. The TypeScript service sits in the middle and runs every step: step 3.",
      model: "Not there. The model only drafts; it never talks to the patient directly: step 4.",
      guard: "Not there. Nothing reaches the patient before the guard checks it: step 5.",
      reply: "Not there. The reply goes last, after the check: step 6.",
    } as Record<TileId, string>,
    placed: (t: string, n: number) => `${t} in step ${n}.`,
    selectedHint: (t: string) => `${t} picked up. Choose its step, or press Escape.`,
    placeHere: (t: string, n: number) => `Place ${t} in step ${n}`,
    remove: (t: string) => `${t}, placed. Activate to take it back out.`,
    stages: [
      "A voice note arrives on LINE (0:04).",
      "“Can I move my cleaning to Saturday?”",
      "The service looks up Saturday's open slots.",
      "The model drafts: “Saturday 10:30 is open. Shall I book it?”",
      "Guard: no promise, no diagnosis, no price outside the list. Passed.",
      "Reply sent. Connected end to end.",
    ],
    replyLabel: "Reply on LINE · fictional clinic",
    reply: "Saturday 10:30 is open. Shall I book it for you?",
    again: "Run again",
    reset: "Reset",
  },
  th: {
    kicker: "ลองเล่น · ประกอบระบบ",
    title: "ต่อระบบผู้ช่วยคลินิกให้ครบ",
    lede: "คนไข้ส่งข้อความเสียงมาทาง LINE ลากชิ้นส่วนไปวางในขั้นที่ถูก หรือแตะชิ้นส่วนแล้วแตะขั้นก็ได้",
    trayLabel: "ชิ้นส่วน",
    trayEmpty: "วางครบทุกชิ้นแล้ว",
    idle: "หกชิ้น หกขั้น อ่านคำใบ้ในแต่ละขั้นดูครับ",
    tiles: {
      line: "LINE",
      stt: "แปลงเสียงเป็นข้อความ",
      ts: "TypeScript",
      model: "โมเดล",
      guard: "ชุดตรวจคำตอบ",
      reply: "ส่งคำตอบ",
    } as Record<TileId, string>,
    sockets: [
      "ช่องทางที่ข้อความเข้ามา",
      "เปลี่ยนเสียงให้เป็นคำ",
      "บริการหลักที่คุมทุกขั้น",
      "ร่างคำตอบ",
      "กันคำที่คลินิกห้ามพูด",
      "ส่งกลับถึงคนไข้",
    ],
    wrong: {
      line: "ยังไม่ใช่ LINE คือช่องทางที่ข้อความเข้ามา อยู่ขั้นที่ 1",
      stt: "ยังไม่ใช่ ข้อความเสียงต้องแปลงเป็นคำก่อน อยู่ขั้นที่ 2",
      ts: "ยังไม่ใช่ บริการ TypeScript อยู่ตรงกลางและคุมทุกขั้น อยู่ขั้นที่ 3",
      model: "ยังไม่ใช่ โมเดลแค่ร่างคำตอบ ไม่ได้คุยกับคนไข้ตรง ๆ อยู่ขั้นที่ 4",
      guard: "ยังไม่ใช่ ทุกคำตอบต้องผ่านชุดตรวจก่อนถึงคนไข้ อยู่ขั้นที่ 5",
      reply: "ยังไม่ใช่ ส่งคำตอบเป็นขั้นสุดท้าย หลังผ่านการตรวจ อยู่ขั้นที่ 6",
    } as Record<TileId, string>,
    placed: (t: string, n: number) => `วาง ${t} ในขั้นที่ ${n} แล้ว`,
    selectedHint: (t: string) => `เลือก ${t} แล้ว เลือกขั้นที่จะวาง หรือกด Escape เพื่อยกเลิก`,
    placeHere: (t: string, n: number) => `วาง ${t} ในขั้นที่ ${n}`,
    remove: (t: string) => `${t} วางแล้ว กดเพื่อเอาออก`,
    stages: [
      "ข้อความเสียงเข้ามาทาง LINE (0:04)",
      "“ขอเลื่อนขูดหินปูนเป็นวันเสาร์ได้ไหมคะ”",
      "บริการเช็คคิวว่างของวันเสาร์",
      "โมเดลร่างคำตอบ: “วันเสาร์ 10:30 ว่างค่ะ จองให้เลยไหมคะ”",
      "ชุดตรวจ: ไม่มีคำสัญญา ไม่วินิจฉัย ไม่มีราคานอกรายการ ผ่าน",
      "ส่งคำตอบแล้ว ต่อครบทุกขั้น",
    ],
    replyLabel: "คำตอบทาง LINE · คลินิกสมมติ",
    reply: "วันเสาร์ 10:30 ว่างค่ะ จองให้เลยไหมคะ",
    again: "ส่งอีกรอบ",
    reset: "เริ่มใหม่",
  },
};
