// Generated by scripts/bake-wordmark.mts. Do not edit by hand.
// Ink box of the baked wordmark relative to the line box origin, in em of the wordmark font size.
export const WORDMARK_EM = {
  x0: 0.08008,
  y0: 0.00391,
  w: 3.24609,
  h: 0.71680,
} as const;
