/*
 * Generated by tools/build-assets.mts (do not edit by hand): the files in public/audio, their loop
 * bodies and crossfade tails (seconds), and the cut points of the sprites.
 */

export type AssetLoop = { body: number; tail: number; correlated: boolean };
export type Segment = { start: number; dur: number };

export const RAIN_WASH = { name: "rain-wash", loop: {body: 24, tail: 0.8, correlated: false} as AssetLoop };
export const RAIN_GLASS = { name: "rain-glass", loop: {body: 16, tail: 0.8, correlated: false} as AssetLoop };
export const THUNDER = { name: "thunder", segments: [{start: 0.25, dur: 13}, {start: 13.5, dur: 13}, {start: 26.75, dur: 13}] as Segment[] };
export const MUSIC = { name: "cozy-loop", loop: {body: 26.666667, tail: 0.75, correlated: true} as AssetLoop };
export const SFX = {
  name: "sfx",
  clinks: [{start: 0.15, dur: 0.4}, {start: 0.7, dur: 0.124}, {start: 0.974, dur: 0.4}, {start: 1.524, dur: 0.124}, {start: 1.798, dur: 0.084}, {start: 2.032, dur: 0.104}, {start: 2.286, dur: 0.159}] as Segment[],
  splashes: [{start: 2.595, dur: 1.4}, {start: 4.145, dur: 1.4}] as Segment[],
  drops: [{start: 5.695, dur: 0.6}, {start: 6.445, dur: 0.6}, {start: 7.195, dur: 0.6}] as Segment[],
};
