// Generated by scripts/vectorize-doodles.ts. Do not edit by hand; re-run the script.

export const artManifest = {
  "era-evening-star": { w: 300, h: 287 },
  "era-laptop-start": { w: 266, h: 299 },
  "era-phone-apps": { w: 270, h: 301 },
  "note-lighthouse": { w: 299, h: 303 },
  "note-measure": { w: 299, h: 260 },
  "note-notebook": { w: 299, h: 212 },
  "note-ship-small": { w: 299, h: 177 },
  "scene-clinic-desk": { w: 473, h: 295 },
  "scene-game-night": { w: 468, h: 320 },
  "scene-helm-crew": { w: 425, h: 321 },
  "scene-paper-plane": { w: 473, h: 156 },
  "scene-qa-lab": { w: 475, h: 256 },
  "scene-storefront": { w: 475, h: 280 },
  "scene-voice-to-text": { w: 474, h: 246 },
  "scene-workbench": { w: 474, h: 263 },
  "portrait-head": { w: 263, h: 246 },
  "portrait-laptop": { w: 473, h: 314 },
  "portrait-paper-plane": { w: 282, h: 397 },
  "portrait-wave": { w: 299, h: 397 },
} as const satisfies Record<string, { w: number; h: number }>;

export type ArtName = keyof typeof artManifest;
