// Generated by scripts/gen-tool-logos.ts from simple-icons 16.34.0. Do not edit by hand; re-run the script.
// The marks are trademarks of their respective owners; use does not imply endorsement.

export type LogoMark = {
  title: string;
  /** Official brand colour, or currentColor for a black mark. */
  color: string;
  /** The theme in which the mark sits on a contrasting tile. */
  badge?: "light" | "dark";
};

/** The sprite with one <symbol> per mark (24x24 viewBox); the query busts caches when it changes. */
export const LOGO_SPRITE = "/tool-logos.svg?v=abb51b1614";

export const logos = {
  typescript: { title: "TypeScript", color: "#3178C6" },
  nodedotjs: { title: "Node.js", color: "#5FA04E" },
  nestjs: { title: "NestJS", color: "#E0234E" },
  fastify: { title: "Fastify", color: "currentColor" },
  graphql: { title: "GraphQL", color: "#E10098" },
  apachekafka: { title: "Apache Kafka", color: "currentColor" },
  python: { title: "Python", color: "#3776AB" },
  react: { title: "React", color: "#61DAFB", badge: "light" },
  nextdotjs: { title: "Next.js", color: "currentColor" },
  vite: { title: "Vite", color: "#9135FF" },
  tailwindcss: { title: "Tailwind CSS", color: "#06B6D4" },
  angular: { title: "Angular", color: "currentColor" },
  mongodb: { title: "MongoDB", color: "#47A248" },
  postgresql: { title: "PostgreSQL", color: "#4169E1" },
  redis: { title: "Redis", color: "#FF4438" },
  sqlite: { title: "SQLite", color: "#003B57", badge: "dark" },
  docker: { title: "Docker", color: "#2496ED" },
  kubernetes: { title: "Kubernetes", color: "#326CE5" },
  googlecloud: { title: "Google Cloud", color: "#4285F4" },
  flydotio: { title: "Fly.io", color: "#24175B", badge: "dark" },
  cloudflare: { title: "Cloudflare", color: "#F38020" },
  vercel: { title: "Vercel", color: "currentColor" },
  vitest: { title: "Vitest", color: "#00FF74", badge: "light" },
  jest: { title: "Jest", color: "#C21325" },
  githubactions: { title: "GitHub Actions", color: "#2088FF" },
  gitlab: { title: "GitLab", color: "#FC6D26" },
  github: { title: "GitHub", color: "currentColor" },
  shopify: { title: "Shopify", color: "#7AB55C" },
  line: { title: "LINE", color: "#00C300" },
  livekit: { title: "LiveKit", color: "#FFFFFF", badge: "light" },
  anthropic: { title: "Anthropic", color: "currentColor" },
  claude: { title: "Claude", color: "#D97757" },
  googlegemini: { title: "Google Gemini", color: "#8E75B2" },
  rust: { title: "Rust", color: "currentColor" },
  bun: { title: "Bun", color: "currentColor" },
  swift: { title: "Swift", color: "#F05138" },
} satisfies Record<string, LogoMark>;

export type LogoSlug = keyof typeof logos;
