/**
 * Extract the brand marks the tools surfaces use from Simple Icons.
 *
 *   pnpm logos:gen
 *
 * `simple-icons` is a devDependency only: the site ships the few marks below, never the package.
 * Marks keep their official colour and proportions. The only change: black (or near-black) marks
 * render in currentColor so they read in the dark theme. A mark whose colour has too little
 * contrast against the chip surface in one theme sits on a contrasting tile in that theme
 * (`badge`) instead of being recoloured. Simple Icons' disclaimer applies: the marks are their
 * owners' trademarks.
 *
 * Output (committed):
 *   public/tool-logos.svg                     one <symbol> per mark, drawn with <use> (one cached
 *                                             request; the path data stays out of every page's
 *                                             HTML and RSC payload)
 *   src/components/tools/logos.generated.ts   title, colour and badge per mark, plus the sprite URL
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import * as icons from "simple-icons";

const OUT = resolve("src/components/tools/logos.generated.ts");
const SPRITE = resolve("public/tool-logos.svg");

/** The marks to extract. `ink`: a black mark, drawn in currentColor. */
const MARKS: { slug: string; ink?: true }[] = [
  { slug: "typescript" },
  { slug: "nodedotjs" },
  { slug: "nestjs" },
  { slug: "fastify", ink: true },
  { slug: "graphql" },
  { slug: "apachekafka", ink: true },
  { slug: "python" },
  { slug: "react" },
  { slug: "nextdotjs", ink: true },
  { slug: "vite" },
  { slug: "tailwindcss" },
  { slug: "angular", ink: true },
  { slug: "mongodb" },
  { slug: "postgresql" },
  { slug: "redis" },
  { slug: "sqlite" },
  { slug: "docker" },
  { slug: "kubernetes" },
  { slug: "googlecloud" },
  { slug: "flydotio" },
  { slug: "cloudflare" },
  { slug: "vercel", ink: true },
  { slug: "vitest" },
  { slug: "jest" },
  { slug: "githubactions" },
  { slug: "gitlab" },
  { slug: "github", ink: true },
  { slug: "shopify" },
  { slug: "line" },
  { slug: "livekit" },
  { slug: "anthropic", ink: true },
  { slug: "claude" },
  { slug: "googlegemini" },
  { slug: "rust", ink: true },
  { slug: "bun", ink: true },
  { slug: "swift" },
];

/** The chip surface (--surface) in each theme, as sRGB. */
const SURFACE = { light: "fcfaf6", dark: "181613" };
/** Below this contrast ratio a mark sits on a disc in that theme. */
const MIN_CONTRAST = 1.6;

function luminance(hex: string): number {
  const [r, g, b] = [0, 2, 4].map((i) => {
    const c = parseInt(hex.slice(i, i + 2), 16) / 255;
    return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

function contrast(a: string, b: string): number {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

type Icon = { slug: string; title: string; hex: string; path: string };
const bySlug = new Map(
  Object.values(icons as unknown as Record<string, Icon>)
    .filter((i) => i && typeof i === "object" && "slug" in i)
    .map((i) => [i.slug, i]),
);

const marks = MARKS.map(({ slug, ink }) => {
  const icon = bySlug.get(slug);
  if (!icon) throw new Error(`simple-icons has no "${slug}"`);
  const badge = ink
    ? []
    : (["light", "dark"] as const).filter((theme) => contrast(icon.hex, SURFACE[theme]) < MIN_CONTRAST);
  if (badge.length > 1) throw new Error(`"${slug}" is low-contrast in both themes`);
  return { slug, icon, color: ink ? "currentColor" : `#${icon.hex}`, badge: badge[0] };
});

const version = JSON.parse(readFileSync(resolve("node_modules/simple-icons/package.json"), "utf8")).version;
const sprite = `<svg xmlns="http://www.w3.org/2000/svg">
<!-- Brand marks from simple-icons ${version} (CC0 collection). Each mark is a trademark of its owner; use does not imply endorsement. -->
${marks.map(({ slug, icon }) => `<symbol id="${slug}" viewBox="0 0 24 24"><path d="${icon.path}"/></symbol>`).join("\n")}
</svg>
`;
writeFileSync(SPRITE, sprite);
const hash = createHash("sha256").update(sprite).digest("hex").slice(0, 10);

writeFileSync(
  OUT,
  `// Generated by scripts/gen-tool-logos.ts from simple-icons ${version}. Do not edit by hand; re-run the script.
// The marks are trademarks of their respective owners; use does not imply endorsement.

export type LogoMark = {
  title: string;
  /** Official brand colour, or currentColor for a black mark. */
  color: string;
  /** The theme in which the mark sits on a contrasting tile. */
  badge?: "light" | "dark";
};

/** The sprite with one <symbol> per mark (24x24 viewBox); the query busts caches when it changes. */
export const LOGO_SPRITE = "/tool-logos.svg?v=${hash}";

export const logos = {
${marks
  .map(({ slug, icon, color, badge }) => {
    const fields = [`title: ${JSON.stringify(icon.title)}`, `color: ${JSON.stringify(color)}`];
    if (badge) fields.push(`badge: ${JSON.stringify(badge)}`);
    return `  ${slug}: { ${fields.join(", ")} },`;
  })
  .join("\n")}
} satisfies Record<string, LogoMark>;

export type LogoSlug = keyof typeof logos;
`,
);
console.log(`wrote ${marks.length} marks to ${SPRITE} and ${OUT}`);
